### PR TITLE
Add Lit v3 support

### PR DESCRIPTION
**Pull request by klasjersevi**
When using lit-modal-portal with a lit v3 project, both v2 and v3 is included and also causes type conflicts. This PR extends the semver range for lit to work with both v2 and v3 and makes lit a peer dependency. It also upgrades all dependencies to latest versions.

### CODE REVIEW

**Comment by klasjersevi** [comment]
Thanks!
For reference: Lit v3 is mainly an internal upgrade of the code with very few changes.

https://lit.dev/docs/releases/upgrade/

> For the vast majority of users there should be no required code changes to upgrade from Lit 2 to Lit 3. Most apps and libraries should be able to extend their npm version ranges to include both 2.x and 3.x, like "^2.7.0 || ^3.0.0".
> 
> Lit 2.x and 3.0 are interoperable – templates, base classes, and directives from one version of Lit will work with those from another.

**Review by nicholas-wilcox — APPROVED** [review]

**Comment by nicholas-wilcox** [comment]
Thanks again, @klasjersevi. I've merged these changes and recorded them in the CHANGELOG before publishing.

**Comment by klasjersevi** [comment]
Great! Don't forget to remove the "-pre" from the semver version in package.json to get a proper release version.

**Comment by nicholas-wilcox** [comment]
Thanks, I think I'm going to give everything a once-over and swap out ImmutableJS for Immer before releasing.

**Comment by klasjersevi** [comment]
The latest npm package (0.5.0-pre) only contains the docs, so you might want to review the packing/publishing.

https://www.npmjs.com/package/lit-modal-portal/v/0.5.0-pre?activeTab=code

**Comment by nicholas-wilcox** [comment]
whoops, my mistake. I unpublished the prerelease version and published 0.5.0, which contains the actual code 😅

**Pull request merged**
